### ISSUE TITLE
Is it working?

### ISSUE THREAD

**Issue by budhh** [IslamAlam/blitzwolf-bw-kb-1#1]
Hey Islam, 
I am new to the mechanical keyboard community and I just found this git page. I didn't know how to contact you cause I wanted to ask a couple of questions. 

- I am a noob, so from what I can gather you have some sort of firmware ready but the Bluetooth does not work. Am I right on this point?
- I just wanna confirm that the keyboard you are writing the firmware for is the "Blitzwolf Keyboard".
- Is this firmware useable?

Much Thanks

**Comment by IslamAlam** [comment]
Hey @LeroyWasKilled,

The firmware is working at the moment but it does not support Bluetooth yet. I am not sure if we can push a Bluetooth support since the keyboard is using SPI for Bluetooth communication and we did not figure it out yet how it works.

I will upload in the release page multiple QMK firmware which is working. 

Here is a video for the keyboard with QMK: https://youtu.be/aAHJMCko2-Y

**Comment by budhh** [comment]
Can I make my own custom key binds, how do I make those?
I saw that I have to use sonix software to flash it, and connect reset and ground while booting it for it to load into bootloader.
Is it possible to use QMK toolbox or QMK configurator?
Is there a place I can contact you? If I need more help.

**Comment by IslamAlam** [comment]
Hi @LeroyWasKilled, 
I am sorry for the late response. I have been working on my MSc thesis and graduation work etc... 

- yes, it is possible to make your own custom key. it is needed to make a new keymap.c and update it according to your needs.
- It is not possible to use QMK toolbox or configurator. I was aware that a few months ago they were working on it in the branch of SonixQMK I am not sure if it is working or not at the moment.
- It is easier to contact me via signal my number: +36703558760

**Comment by Duck0021** [comment]
hello recently I installed a windows that caused me several problems and one of them was a black screen so I restarted my pc several times by the reset button and now my keyboard does not work it lights up the leds more and as if it were disconnected from the usb the pc does not recognize it you could you help me pls

**Comment by IslamAlam** [comment]
> hello recently I installed a windows that caused me several problems and one of them was a black screen so I restarted my pc several times by the reset button and now my keyboard does not work it lights up the leds more and as if it were disconnected from the usb the pc does not recognize it you could you help me pls

Hey, you can try to put the keyboard in the firmware boot mode, so you can install the firmware. 
[](https://github.com/IslamAlam/blitzwolf-bw-kb-1#key-matrix--mcu)Using the ground point hold the boot pin to ground while turning on the power. 
Then use the software to flash the firmware. You can install first the original firmware and see if it works or not.
